name: Auto Generate Solar Activity Video

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution automatique chaque jour à 01h00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily solar activity script
        run: python autovideo_daily.py

      - name: Upload final videos as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: solar_activity_videos_daily
          path: solar_activity_videos/daily/**/*.mp4

      - name: Commit all modified/generated files in one commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Ajouter JSON + vidéos
          git add Protons/daily || true
          git add solar_activity_videos/daily/**/*.mp4 || true

          # Faire un seul commit si modifications
          if ! git diff --cached --quiet; then
            git commit -m "Daily update: proton JSON and video $(date +'%d:%m:%Y')"
            git push
          else
            echo "Aucun changement à committer"
          fi
